contact_links:
  - name: Are you looking for documentation on this project?
    url: https://maehr.github.io/Sexueller-Missbrauch-im-Umfeld-der-katholischen-Kirche-in-der-Schweiz
    about: Please see the documentation for this project on its GitHub Pages page.
  - name: Do you want to discuss this project with the community?
    url: https://github.com/maehr/Sexueller-Missbrauch-im-Umfeld-der-katholischen-Kirche-in-der-Schweiz/discussions
    about: Please see the discussions page for this project.
blank_issues_enabled: true
