services:
  mediawiki:
    container_name: mediawiki
    build: ..
    ports:
      - '8080:80'
    volumes:
      - mediawiki_images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      MW_DB_TYPE: mysql
      MW_DB_SERVER: ${DB_SERVER}
      MW_DB_NAME: ${DB_NAME}
      MW_DB_USER: ${DB_USER}
      MW_DB_PASSWORD: ${DB_PASSWORD}
      MW_SERVER: ${MW_SERVER}
      MW_SECRET_KEY: ${MW_SECRET_KEY}
      MW_UPGRADE_KEY: ${MW_UPGRADE_KEY}
      MW_DEBUG: ${MW_DEBUG}
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: mariadb:11
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - '443:443'
      - '8443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mediawiki
    restart: always

volumes:
  mediawiki_images:
  db_data:
  caddy_data:
  caddy_config:
