<?php
# This file was automatically generated by the MediaWiki 1.42.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = 'Sexueller Missbrauch im Umfeld der katholischen Kirche in der Schweiz seit Mitte des 20. Jahrhunderts';
$wgMetaNamespace = 'Sexueller_Missbrauch_im_Umfeld_der_katholischen_Kirche_in_der_Schweiz_seit_Mitte_des_20._Jahrhunderts';

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '';

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv('MW_SERVER') ?: 'https://localhost';

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/uzh-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/uzh-logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = '';
$wgPasswordSender = '';

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = 'mysql';
$wgDBserver = getenv('MW_DB_SERVER') ?: 'db';
$wgDBname = getenv('MW_DB_NAME') ?: 'my_wiki';
$wgDBuser = getenv('MW_DB_USER') ?: 'wikiuser';
$wgDBpassword = getenv('MW_DB_PASSWORD') ?: 'wikipassword';

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgMaxUploadSize = 1024 * 1024 * 50; // Set upload limit to 50MB
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = '/usr/bin/convert';
$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'doc', 'xls', 'mpp', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx', 'pptx', 'ps', 'odt', 'ods', 'odp', 'odg', 'csv', 'tsv' ];
$wgPdfOutputExtension = 'png';  // The format for PDF thumbnails (PNG format)

// $wgTrustedMediaFormats[] = 'application/pdf';
$wgVerifyMimeType = false;

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = 'de-ch';

# Time zone
$wgLocaltimezone = 'Europe/Zurich';

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = getenv('MW_SECRET_KEY') ?: '7c76a443263ec61560964f95a698024d49487f962a154e10f2dbf7b26a48d4d5';

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = '1';

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = getenv('MW_UPGRADE_KEY') ?: '2381edfb0e189026';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = '';
$wgRightsText = '';
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = '/usr/bin/diff3';

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['autoconfirmed']['upload'] = true;  // Allows autoconfirmed users to upload files
$wgGroupPermissions['user']['upload'] = true;  // Allow all registered users to upload
$wgGroupPermissions['*']['upload'] = false;  // Prevent anonymous users from uploading

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = 'vector';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'Cargo' );
wfLoadExtension( 'DataTransfer' );
wfLoadExtension( 'PageForms' );
wfLoadExtension( 'PageSchemas' );
wfLoadExtension( 'PdfBook' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'VisualEditor' );


# End of automatically generated settings.

# Add more configuration options below.

# Deactivate caching
$wgCachePages = false;
$wgEnableParserCache = false;
$wgParserCacheType = CACHE_NONE;
$wgUseFileCache = false;

# Allow urls with file://
$wgUrlProtocols[] = "file://";

# Enable tabs for PDF export
$wgPdfBookTab = true;

# DEBUG
$wgDebugToolbar = getenv('MW_DEBUG') ?: false;
$wgDebugComments = getenv('MW_DEBUG') ?: false;
$wgDevelopmentWarnings = getenv('MW_DEBUG') ?: false;
$wgShowExceptionDetails = getenv('MW_DEBUG') ?: false;
$wgShowDBErrorBacktrace = getenv('MW_DEBUG') ?: false;
$wgShowSQLErrors = getenv('MW_DEBUG') ?: false;
$wgDebugDumpSql = getenv('MW_DEBUG') ?: false;
$wgDebugLogGroups['SQL'] = './sql.log';
